trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install dotnet 8.0 SDK'
  inputs:
    version: '8.0.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  displayName: 'Build the solution'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Run the tests'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'Packing'
  inputs:
    command: 'pack'
    versioningScheme: byEnvVar
    versionEnvVar: PackageVersion
    packagesToPack: '**/RestMockCore.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Publish the package'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
