trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install dotnet 6.0 SDK'
  inputs:
    version: '6.0.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  displayName: 'Build the solution'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Run the tests'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'Packing'
  inputs:
    command: 'pack'
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: PackageVersion
    packagesToPack: '**/RestMockCore.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Publish the package'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
# - task: NuGetCommand@2
#   displayName: 'Push to nuget.org'
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'Nuget rest-mock-core'
